# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpio.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ngpio.proto\"?\n\x0eSetGpioRequest\x12\x12\n\nGpioNumber\x18\x01 \x01(\r\x12\x19\n\x05State\x18\x02 \x01(\x0e\x32\n.GpioState\"$\n\x0eGetGpioRequest\x12\x12\n\nGpioNumber\x18\x01 \x01(\r\"@\n\x0fGetGpioResponse\x12\x12\n\nGpioNumber\x18\x01 \x01(\r\x12\x19\n\x05State\x18\x02 \x01(\x0e\x32\n.GpioState\"\x11\n\x0fSetGpioResponse\"6\n\x10\x42linkGpioRequest\x12\x12\n\nGpioNumber\x18\x01 \x01(\r\x12\x0e\n\x06Length\x18\x02 \x01(\x01\"7\n\x11\x42linkGpioResponse\x12\x12\n\nGpioNumber\x18\x01 \x01(\r\x12\x0e\n\x06Length\x18\x02 \x01(\x01*\x1c\n\tGpioState\x12\x07\n\x03Off\x10\x00\x12\x06\n\x02On\x10\x01\x32\x9c\x01\n\x04Gpio\x12.\n\x07GetGpio\x12\x0f.GetGpioRequest\x1a\x10.GetGpioResponse\"\x00\x12.\n\x07SetGpio\x12\x0f.SetGpioRequest\x1a\x10.SetGpioResponse\"\x00\x12\x34\n\tBlinkGpio\x12\x11.BlinkGpioRequest\x1a\x12.BlinkGpioResponse\"\x00\x62\x06proto3')
)

_GPIOSTATE = _descriptor.EnumDescriptor(
  name='GpioState',
  full_name='GpioState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Off', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='On', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=315,
  serialized_end=343,
)
_sym_db.RegisterEnumDescriptor(_GPIOSTATE)

GpioState = enum_type_wrapper.EnumTypeWrapper(_GPIOSTATE)
Off = 0
On = 1



_SETGPIOREQUEST = _descriptor.Descriptor(
  name='SetGpioRequest',
  full_name='SetGpioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GpioNumber', full_name='SetGpioRequest.GpioNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='State', full_name='SetGpioRequest.State', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=77,
)


_GETGPIOREQUEST = _descriptor.Descriptor(
  name='GetGpioRequest',
  full_name='GetGpioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GpioNumber', full_name='GetGpioRequest.GpioNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=115,
)


_GETGPIORESPONSE = _descriptor.Descriptor(
  name='GetGpioResponse',
  full_name='GetGpioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GpioNumber', full_name='GetGpioResponse.GpioNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='State', full_name='GetGpioResponse.State', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=181,
)


_SETGPIORESPONSE = _descriptor.Descriptor(
  name='SetGpioResponse',
  full_name='SetGpioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=200,
)


_BLINKGPIOREQUEST = _descriptor.Descriptor(
  name='BlinkGpioRequest',
  full_name='BlinkGpioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GpioNumber', full_name='BlinkGpioRequest.GpioNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Length', full_name='BlinkGpioRequest.Length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=256,
)


_BLINKGPIORESPONSE = _descriptor.Descriptor(
  name='BlinkGpioResponse',
  full_name='BlinkGpioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GpioNumber', full_name='BlinkGpioResponse.GpioNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Length', full_name='BlinkGpioResponse.Length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=313,
)

_SETGPIOREQUEST.fields_by_name['State'].enum_type = _GPIOSTATE
_GETGPIORESPONSE.fields_by_name['State'].enum_type = _GPIOSTATE
DESCRIPTOR.message_types_by_name['SetGpioRequest'] = _SETGPIOREQUEST
DESCRIPTOR.message_types_by_name['GetGpioRequest'] = _GETGPIOREQUEST
DESCRIPTOR.message_types_by_name['GetGpioResponse'] = _GETGPIORESPONSE
DESCRIPTOR.message_types_by_name['SetGpioResponse'] = _SETGPIORESPONSE
DESCRIPTOR.message_types_by_name['BlinkGpioRequest'] = _BLINKGPIOREQUEST
DESCRIPTOR.message_types_by_name['BlinkGpioResponse'] = _BLINKGPIORESPONSE
DESCRIPTOR.enum_types_by_name['GpioState'] = _GPIOSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetGpioRequest = _reflection.GeneratedProtocolMessageType('SetGpioRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETGPIOREQUEST,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:SetGpioRequest)
  ))
_sym_db.RegisterMessage(SetGpioRequest)

GetGpioRequest = _reflection.GeneratedProtocolMessageType('GetGpioRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETGPIOREQUEST,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:GetGpioRequest)
  ))
_sym_db.RegisterMessage(GetGpioRequest)

GetGpioResponse = _reflection.GeneratedProtocolMessageType('GetGpioResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETGPIORESPONSE,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:GetGpioResponse)
  ))
_sym_db.RegisterMessage(GetGpioResponse)

SetGpioResponse = _reflection.GeneratedProtocolMessageType('SetGpioResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETGPIORESPONSE,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:SetGpioResponse)
  ))
_sym_db.RegisterMessage(SetGpioResponse)

BlinkGpioRequest = _reflection.GeneratedProtocolMessageType('BlinkGpioRequest', (_message.Message,), dict(
  DESCRIPTOR = _BLINKGPIOREQUEST,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:BlinkGpioRequest)
  ))
_sym_db.RegisterMessage(BlinkGpioRequest)

BlinkGpioResponse = _reflection.GeneratedProtocolMessageType('BlinkGpioResponse', (_message.Message,), dict(
  DESCRIPTOR = _BLINKGPIORESPONSE,
  __module__ = 'gpio_pb2'
  # @@protoc_insertion_point(class_scope:BlinkGpioResponse)
  ))
_sym_db.RegisterMessage(BlinkGpioResponse)



_GPIO = _descriptor.ServiceDescriptor(
  name='Gpio',
  full_name='Gpio',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=346,
  serialized_end=502,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetGpio',
    full_name='Gpio.GetGpio',
    index=0,
    containing_service=None,
    input_type=_GETGPIOREQUEST,
    output_type=_GETGPIORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetGpio',
    full_name='Gpio.SetGpio',
    index=1,
    containing_service=None,
    input_type=_SETGPIOREQUEST,
    output_type=_SETGPIORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BlinkGpio',
    full_name='Gpio.BlinkGpio',
    index=2,
    containing_service=None,
    input_type=_BLINKGPIOREQUEST,
    output_type=_BLINKGPIORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPIO)

DESCRIPTOR.services_by_name['Gpio'] = _GPIO

# @@protoc_insertion_point(module_scope)
